# Generated by Django 5.2.14 on 2026-05-12 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('platform', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('rating', models.IntegerField()),
                ('description', models.TextField(max_length=250)),
            ],
        ),
    ]
